/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Today */
        get: operations["get_today_v1_dashboard_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description The ledger, optionally narrowed to one category. Drafts and chips are never narrowed.
         */
        get: operations["get_activity_v1_transactions_get"];
        put?: never;
        /**
         * Post Transaction
         * @description Add spending. It lands as a draft whatever route it came in by.
         */
        post: operations["post_transaction_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Confirm */
        post: operations["post_confirm_v1_transactions__transaction_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Discard */
        post: operations["post_discard_v1_transactions__transaction_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}/unconfirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Unconfirm */
        post: operations["post_unconfirm_v1_transactions__transaction_id__unconfirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/thread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Default Thread
         * @description The user's conversation, created on first ask.
         */
        get: operations["get_default_thread_v1_butler_thread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_v1_butler_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/threads/{thread_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Message */
        post: operations["post_message_v1_butler_threads__thread_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Default Message
         * @description Ask without naming a thread. The client almost always wants this one.
         */
        post: operations["post_default_message_v1_butler_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/approvals/{approval_id}/respond": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Respond */
        post: operations["respond_v1_butler_approvals__approval_id__respond_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/memories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Memories
         * @description Everything Kira believes about this user, in the order it is retrieved.
         */
        get: operations["list_memories_v1_butler_memories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/butler/memories/{memory_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Memory */
        delete: operations["delete_memory_v1_butler_memories__memory_id__delete"];
        options?: never;
        head?: never;
        /** Correct Memory */
        patch: operations["correct_memory_v1_butler_memories__memory_id__patch"];
        trace?: never;
    };
    "/v1/capture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Availability
         * @description What the client may offer. A dead affordance is worse than none.
         */
        get: operations["availability_v1_capture_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capture/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Receipt */
        post: operations["read_receipt_v1_capture_receipt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capture/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Read Voice */
        post: operations["read_voice_v1_capture_voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_v1_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/foresight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Foresight */
        get: operations["get_foresight_v1_foresight_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/foresight/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Scenarios */
        post: operations["post_scenarios_v1_foresight_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/briefings/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Today Briefing
         * @description The prepared morning inbox, if the nightly worker has run already.
         */
        get: operations["get_today_briefing_v1_briefings_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/briefings/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Briefing
         * @description Run today's worker path now. A retry returns the original briefing.
         */
        post: operations["run_briefing_v1_briefings_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityDayResponse */
        ActivityDayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Total Sen */
            total_sen: number;
            /** Transactions */
            transactions: components["schemas"]["TransactionResponse"][];
        };
        /** ActivityResponse */
        ActivityResponse: {
            /** Drafts */
            drafts: components["schemas"]["TransactionResponse"][];
            /** Draft Total Sen */
            draft_total_sen: number;
            /** Days */
            days: components["schemas"]["ActivityDayResponse"][];
            /** Spent This Cycle Sen */
            spent_this_cycle_sen: number;
            /** Categories */
            categories: components["schemas"]["CategorySummaryResponse"][];
        };
        /** ApprovalDecisionRequest */
        ApprovalDecisionRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "accept" | "edit" | "reject";
            /** Args */
            args?: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_read_receipt_v1_capture_receipt_post */
        Body_read_receipt_v1_capture_receipt_post: {
            /** Image */
            image: string;
        };
        /** Body_read_voice_v1_capture_voice_post */
        Body_read_voice_v1_capture_voice_post: {
            /** Audio */
            audio: string;
        };
        /** BriefingInboxResponse */
        BriefingInboxResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * On Date
             * Format: date
             */
            on_date: string;
            /** Summary */
            summary: string;
            /** Proposal Count */
            proposal_count: number;
            /** Pending Proposal Count */
            pending_proposal_count: number;
        };
        /** BriefingRunResponse */
        BriefingRunResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * On Date
             * Format: date
             */
            on_date: string;
            /** Summary */
            summary: string;
            /** Proposal Count */
            proposal_count: number;
            /** Created */
            created: boolean;
        };
        /** ButlerApprovalResponse */
        ButlerApprovalResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Thread Id
             * Format: uuid
             */
            thread_id: string;
            /** Tool */
            tool: string;
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
            /** Evidence */
            evidence: [
                string,
                string
            ][];
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ButlerAskRequest */
        ButlerAskRequest: {
            /** Text */
            text: string;
            /** Attachment */
            attachment?: {
                [key: string]: unknown;
            } | null;
        };
        /** ButlerMessageResponse */
        ButlerMessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Evidence */
            evidence: [
                string,
                string
            ][];
            /** Attachment */
            attachment: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ButlerThreadResponse */
        ButlerThreadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Messages */
            messages: components["schemas"]["ButlerMessageResponse"][];
            /** Pending Approvals */
            pending_approvals: components["schemas"]["ButlerApprovalResponse"][];
        };
        /**
         * CaptureAvailability
         * @description Whether the affordances should be offered at all.
         */
        CaptureAvailability: {
            /** Receipt */
            receipt: boolean;
            /** Voice */
            voice: boolean;
            /** Max Bytes */
            max_bytes: number;
        };
        /** CaptureFieldResponse */
        CaptureFieldResponse: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Confidence */
            confidence: number;
        };
        /**
         * CaptureResponse
         * @description What a reader made of a photo or a recording. Nothing is on the ledger.
         */
        CaptureResponse: {
            /** Kind */
            kind: string;
            /** Source */
            source: string;
            /** Merchant */
            merchant: string;
            /** Amount Sen */
            amount_sen: number;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: number;
            /** Note */
            note: string;
            /** Transcript */
            transcript: string;
            /** Fields */
            fields: components["schemas"]["CaptureFieldResponse"][];
        };
        /** CategoryResponse */
        CategoryResponse: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
        };
        /** CategorySummaryResponse */
        CategorySummaryResponse: {
            /** Slug */
            slug: string;
            /** Label */
            label: string;
            /** Spent This Cycle Sen */
            spent_this_cycle_sen: number;
            /** Count */
            count: number;
        };
        /** CreateTransactionRequest */
        CreateTransactionRequest: {
            /** Merchant */
            merchant: string;
            /** Amount Sen */
            amount_sen: number;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /**
             * Category
             * @default uncategorised
             */
            category: string;
            /**
             * Source
             * @default manual
             */
            source: string;
            /** Confidence */
            confidence?: number | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** DashboardTodayResponse */
        DashboardTodayResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Display Name */
            display_name: string;
            /** Currency */
            currency: string;
            /** Balance Sen */
            balance_sen: number;
            /** Reserved Sen */
            reserved_sen: number;
            /** Buffer Sen */
            buffer_sen: number;
            /** Goal Reserve Sen */
            goal_reserve_sen: number;
            /** Unclaimed Sen */
            unclaimed_sen: number;
            /** Per Day Sen */
            per_day_sen: number;
            /** Spent Today Sen */
            spent_today_sen: number;
            /** Safe Today Sen */
            safe_today_sen: number;
            /** Days To Payday */
            days_to_payday: number;
            /** Cycle Elapsed */
            cycle_elapsed: number;
            /** Commitment Count */
            commitment_count: number;
            /** Drafts Waiting */
            drafts_waiting: number;
            next_commitment: components["schemas"]["NextCommitmentResponse"] | null;
            /** Goals */
            goals: components["schemas"]["GoalSummaryResponse"][];
        };
        /** DriverOut */
        DriverOut: {
            lever: components["schemas"]["LeverOut"];
            /** Probability Bp Before */
            probability_bp_before: number;
            /** Probability Bp After */
            probability_bp_after: number;
            /** Bp Per Ringgit */
            bp_per_ringgit: number;
        };
        /** ForesightResponse */
        ForesightResponse: {
            /** Horizon Days */
            horizon_days: number;
            /** Dates */
            dates: string[];
            /** P10 */
            p10: components["schemas"]["MoneyOut"][];
            /** P50 */
            p50: components["schemas"]["MoneyOut"][];
            /** P90 */
            p90: components["schemas"]["MoneyOut"][];
            /** Outlooks */
            outlooks: components["schemas"]["GoalOutlookOut"][];
            /** Drivers */
            drivers: components["schemas"]["DriverOut"][];
            /** Profile Days */
            profile_days: number;
            /** Assumption */
            assumption: string;
        };
        /** GoalOutlookOut */
        GoalOutlookOut: {
            /** Goal Id */
            goal_id: string;
            /**
             * Target Date
             * Format: date
             */
            target_date: string;
            /** Probability Bp */
            probability_bp: number;
            median_shortfall: components["schemas"]["MoneyOut"];
        };
        /** GoalSummaryResponse */
        GoalSummaryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Horizon */
            horizon: string;
            /** Target Sen */
            target_sen: number;
            /** Saved Sen */
            saved_sen: number;
            /** Monthly Sen */
            monthly_sen: number;
            /** Months Left */
            months_left: number;
            /** Note */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeverIn */
        LeverIn: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "goal_monthly" | "commitment_amount" | "daily_spend";
            /** Target Id */
            target_id: string;
            /** Delta Sen */
            delta_sen: number;
        };
        /** LeverOut */
        LeverOut: {
            /** Kind */
            kind: string;
            /** Target Id */
            target_id: string;
            delta: components["schemas"]["MoneyOut"];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MemoryCorrectionRequest */
        MemoryCorrectionRequest: {
            /** Fact */
            fact: string;
        };
        /** MemoryResponse */
        MemoryResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Kind */
            kind: string;
            /** Subject */
            subject: string;
            /** Fact */
            fact: string;
            /** Confidence */
            confidence: number;
            /** Source Message Id */
            source_message_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** MoneyOut */
        MoneyOut: {
            /** Sen */
            sen: number;
            /** Currency */
            currency: string;
        };
        /** NextCommitmentResponse */
        NextCommitmentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Amount Sen */
            amount_sen: number;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Days Until */
            days_until: number;
            /** Protected */
            protected: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** ScenarioComparisonResponse */
        ScenarioComparisonResponse: {
            /** Results */
            results: components["schemas"]["ScenarioResultOut"][];
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /**
             * Horizon Days
             * @default 180
             */
            horizon_days: number;
            /** Levers */
            levers: components["schemas"]["LeverIn"][];
        };
        /** ScenarioResultOut */
        ScenarioResultOut: {
            lever: components["schemas"]["LeverOut"];
            /** Outlooks */
            outlooks: components["schemas"]["GoalOutlookOut"][];
            safe_today_after: components["schemas"]["MoneyOut"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** TransactionResponse */
        TransactionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Merchant */
            merchant: string;
            /** Amount Sen */
            amount_sen: number;
            /** Category */
            category: string;
            /** Category Label */
            category_label: string;
            /**
             * Occurred On
             * Format: date
             */
            occurred_on: string;
            /** Status */
            status: string;
            /** Source */
            source: string;
            /** Confidence */
            confidence: number | null;
            /** Note */
            note: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Currency */
            currency: string;
            /** Buffer Sen */
            buffer_sen: number;
            /**
             * Next Payday
             * Format: date
             */
            next_payday: string;
            /**
             * Cycle Start
             * Format: date
             */
            cycle_start: string;
            /** Cycle Days */
            cycle_days: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    register_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_today_v1_dashboard_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardTodayResponse"];
                };
            };
        };
    };
    get_activity_v1_transactions_get: {
        parameters: {
            query?: {
                category?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_transaction_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_confirm_v1_transactions__transaction_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_discard_v1_transactions__transaction_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_unconfirm_v1_transactions__transaction_id__unconfirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_default_thread_v1_butler_thread_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ButlerThreadResponse"];
                };
            };
        };
    };
    get_thread_v1_butler_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ButlerThreadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_v1_butler_threads__thread_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ButlerAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_default_message_v1_butler_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ButlerAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    respond_v1_butler_approvals__approval_id__respond_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                approval_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_memories_v1_butler_memories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"][];
                };
            };
        };
    };
    delete_memory_v1_butler_memories__memory_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_memory_v1_butler_memories__memory_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memory_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MemoryCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    availability_v1_capture_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureAvailability"];
                };
            };
        };
    };
    read_receipt_v1_capture_receipt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_read_receipt_v1_capture_receipt_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_voice_v1_capture_voice_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_read_voice_v1_capture_voice_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_categories_v1_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryResponse"][];
                };
            };
        };
    };
    get_foresight_v1_foresight_get: {
        parameters: {
            query?: {
                horizon?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForesightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_scenarios_v1_foresight_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_today_briefing_v1_briefings_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingInboxResponse"] | null;
                };
            };
        };
    };
    run_briefing_v1_briefings_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BriefingRunResponse"];
                };
            };
        };
    };
}
