import type { components } from "./src/schema";

export type Schemas = components["schemas"];
export type Activity = Schemas["ActivityResponse"];
export type ActivityDay = Schemas["ActivityDayResponse"];
export type CategorySummary = Schemas["CategorySummaryResponse"];
export type DashboardToday = Schemas["DashboardTodayResponse"];
export type GoalSummary = Schemas["GoalSummaryResponse"];
export type NextCommitment = Schemas["NextCommitmentResponse"];
export type Place = Schemas["PlaceResponse"];
export type DayPlan = Schemas["DayPlanResponse"];
export type PlanDraft = Schemas["PlanDraftRequest"];
export type ButlerThread = Schemas["ButlerThreadResponse"];
export type ButlerMessage = Schemas["ButlerMessageResponse"];
export type ButlerApproval = Schemas["ButlerApprovalResponse"];
export type Memory = Schemas["MemoryResponse"];
export type Capture = Schemas["CaptureResponse"];
export type CaptureField = Schemas["CaptureFieldResponse"];
export type CaptureAvailability = Schemas["CaptureAvailability"];
export type TokenResponse = Schemas["TokenResponse"];
export type Transaction = Schemas["TransactionResponse"];
export type TransactionCorrection = Schemas["CorrectTransactionRequest"];
export type UserResponse = Schemas["UserResponse"];
export type { components, paths } from "./src/schema";
